version: "3.2"

services:
  dev:
    container_name: tea-layer1
    image: paritytech/ci-linux:production
    working_dir: /var/www/tea-layer1
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/tea-layer1/.cargo
    volumes:
      - .:/var/www/tea-layer1
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/tea-layer1 --dev --ws-external"
