version: "3.2"

services:
  dev:
    container_name: tea-layer1-dev
    image: tearust/tea-layer1:latest
    ports:
      - "9944:9944"
    volumes:
      - ./docker/.local:/root/.local

  build:
    container_name: tea-layer1-build
    image: paritytech/ci-linux:production
    working_dir: /tearust/tea-layer1
    environment:
      - CARGO_HOME=/tearust/tea-layer1/docker/.cargo
    volumes:
      - ../:/tearust
      - type: bind
        source: ./docker/.local
        target: /root/.local
    command: bash -c "cargo build --target-dir /tearust/tea-layer1/docker/target"