version: "3.2"

services:
  dev:
    container_name: tea-layer1
    image: paritytech/ci-linux:production
    working_dir: /tearust/tea-layer1
    environment:
      - CARGO_HOME=/tearust/tea-layer1/.cargo
    ports:
      - "9944:9944"
    volumes:
      - ..:/tearust
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --target-dir /tearust/docker-output/tea-layer1 && /tearust/docker-output/tea-layer1/debug/tea-layer1 --dev --ws-external"
  build:
    container_name: tea-layer1-build
    image: paritytech/ci-linux:production
    working_dir: /tearust/tea-layer1
    environment:
      - CARGO_HOME=/tearust/tea-layer1/.cargo
    volumes:
      - ../:/tearust
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --target-dir /tearust/docker-output/tea-layer1"